### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/pushover#1]
@casperboone  Ping me when ready, then I'll do a code review

**Comment by casperboone** [comment]
@freekmurze Ready :)

**Comment by freekmurze** [comment]
Ok, hold off from making commits for the coming half hour.

**Comment by freekmurze** [comment]
Ok, I made some changes, nothing big, all details.

However the tests seems to fail. You'll need to use something like `orchestra/testbench` to make 'm pass on Travis.

**Comment by casperboone** [comment]
Thanks! Made one comment, https://github.com/laravel-notification-channels/pushover/commit/3eae0e724de44b341019547bb60a61fba22b2ea8#commitcomment-18624165, but agree with everything else.

Will look into the tests, was only running them in a Laravel app until now ;).

**Comment by casperboone** [comment]
Fixed the tests.

**Comment by freekmurze** [comment]
Great! Big thumbs up for those integration tests!

**Comment by casperboone** [comment]
Thanks :)
