### ISSUE TITLE
Send Multiple Push Notifications

### ISSUE THREAD

**Issue by vmitchell85** [laravel-notification-channels/pushover#18]
I'm in need of a way to send multiple notifications for a single notifiable. I am familiar with Group notifications but that will not work for my use case.

I've accomplished this by making some modifications to the PushoverChannel@send method but I'm not too good with writing tests (Still working through Adam's Test Driven Laravel).

Basically I'm converting the `routeNotificationFor` response to an array and then looping over them and sending a notification to each one. The details section below shows the code for the send method.

I wasn't sure if I should create a PR, since it wouldn't have tests.

Thanks for taking a look.

<details>

```php
public function send($notifiable, Notification $notification)
    {
        if (! $pushoverReceivers = $notifiable->routeNotificationFor('pushover')) {
            return;
        }

        $pushoverReceivers = is_array($pushoverReceivers) ? $pushoverReceivers : [$pushoverReceivers];

        foreach( $pushoverReceivers as $pushoverReceiver ){
            if (is_string($pushoverReceiver)) {
                $pushoverReceiver = PushoverReceiver::withUserKey($pushoverReceiver);
            }

            $message = $notification->toPushover($notifiable);

            try {
                $this->pushover->send(array_merge($message->toArray(), $pushoverReceiver->toArray()));
            } catch (ServiceCommunicationError $serviceCommunicationError) {
                $this->fireFailedEvent($notifiable, $notification, $serviceCommunicationError->getMessage());
            }
        }

    }
```
</details>

**Comment by vmitchell85** [comment]
As a workaround I created a class that extends `PushoverChannel` and bound it in my `AppServiceProvider`. It was a bit tricky since I had to replicate the `Pushover` class when/needs/give.

**Comment by casperboone** [comment]
Hi @vmitchell85, thanks for the issue. I appreciate it that you took the time to write it down and provide a code sample.

However, I'm a bit reluctant to make this change, because (as far as I know) it is not very common for notification channels to support that.

I'm not sure what your use case is, but isn't it possible to create entities for the receivers on your end and do something like:
```php
foreach($tokens as $token) {
    $receiver = new App\Receiver($token);
    $receiver->notify(new SomeNotification());
}
```
(a bit verbose, but just trying to make the point ;) )
Of course, you can user something else instead of `Receiver` that fits your domain better.

If this doesn't suffice, I'm happy to hear more about the use case and will try to think of a more appropriate solution.

**Comment by vmitchell85** [comment]
I agree that it probably isn't very common. I'm using Spark and creating an application where users create an 'item' that can have multiple different types of notifications associated with it. These notifications are configured and shared between the team so they can be assigned to multiple 'items'.

Therefore the pushover notification might need to go to two different people that would never otherwise share a notification though they both have other 'items' they would like to be notified on.

Hope that makes sense. The issue is that the 'item' is the one I have being notified, but the channel doesn't necessarily have to be directly associated with a user, or a team.

Thanks for taking the time to consider. I figured though it is probably not a very often used scenario that it isn't that big of a change and might be considered.

Regardless, thanks for building the channel! I'm definitely using it one way or another!

**Comment by casperboone** [comment]
Cool, if you have any other issues feel free to discuss them!
