### ISSUE TITLE
Wrong version installed

### ISSUE THREAD

**Issue by BramRoets** [laravel-notification-channels/pushover#21]
When running `composer require laravel-notification-channels/pushover` version 1.1.0 gets installed which does not support Laravel 5.5

The latest release which does support Laravel 5.5 has a lower version (1.0.2). Manually installing this version does off course works. Probably something went wrong naming this release.

**Comment by casperboone** [comment]
Oops, made a little error versioning the release. Thanks for reporting this!

**Comment by casperboone** [comment]
Fixed!
