### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by tylergets** [laravel-notification-channels/pushover#24]
Pushover added support for image pushing January of this year. https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30

It would be great to support this in the package.

**Comment by casperboone** [comment]
Good suggestion! I'd happily accept a PR for this :)

**Comment by boryn** [comment]
I have just prepared a pull request for this: https://github.com/laravel-notification-channels/pushover/pull/49

**Comment by atymic** [comment]
Closed in #49
