### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by CmdrSharp** [laravel-notification-channels/pushover#29]
Support should be added for Laravel 5.8. If no one else can, I'll try to take a look at it when I can find the time.

**Comment by stefnats** [comment]
+1 for accepting your PR.
This is the only dependency which prevents me from upgrading.
Is this project still alive?

**Comment by stefnats** [comment]
@CmdrSharp seems like this project is not maintained anymore (regularly) - Could you provide your fork as a composer package to help people upgrade to Laravel `^5.8`?

**Comment by CmdrSharp** [comment]
@stefnats So it would seem. I've wound up removing my dependency for this package, and as a result likely wouldn't be up for maintaining it myself either. You are free however to fork my fork and publish it if you wish!

**Comment by casperboone** [comment]
Just tagged 2.0.0 with 5.8 support, sorry for the delay!
