### ISSUE TITLE
Dependency issue in Laravel 5.8

### ISSUE THREAD

**Issue by rehmatworks** [laravel-notification-channels/pushover#35]
I'm using Laravel 5.8 and the installation fails:

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/translation v4.3.3
    - Conclusion: don't install symfony/translation v4.3.3
    - .............................
```

Please help.

**Comment by casperboone** [comment]
There was an issue with the Carbon dependency. It's probably fixed in version 2.0.1. This version is not available on packagist yet (might take a while), but you can use the dev-master version.
