### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/pushover#36]

**Comment by atymic** [comment]
Thanks @casperboone :)

**Comment by casperboone** [comment]
Most thanks to @dyusha ❤️

**Comment by dyusha** [comment]
@casperboone could you please push the new release to packagist?

**Comment by atymic** [comment]
@themsaid needs to fix the repo webhooks.

**Comment by atymic** [comment]
Re-opening this while we wait for packagist.

**Comment by casperboone** [comment]
See above :). You can use `dev-master` as the version for now.

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄

**Comment by casperboone** [comment]
Thx for taking care of this @atymic!
