### ISSUE TITLE
Support for on demand notifications

### ISSUE THREAD

**Issue by gabrieltakacs** [laravel-notification-channels/pushover#46]
Please, add support for on-demand notifications (without Notifiable object). See https://laravel.com/docs/8.x/notifications#on-demand-notifications

It should work like:
```
     \Notification::route(PushoverChannel::class, '4fefd4acsad5f4de8f')
            ->notify(
                new MyNotification()
            );
```

If possible, please, backport it also to `2.0` version. Thanks.

**Comment by casperboone** [comment]
Hi @gabrieltakacs,

Luckily, on-demand notifications should already work :). I think, however, that you got the "channel key" wrong. Instead of the fqn it should just be the string "pushover". Here's an example for you that may help:

```php
Notification::route('pushover', '4fefd4acsad5f4de8f')->notify(new AccountApproved)
```

Let me know if this helps and whether you have any other questions 😄

**Comment by gabrieltakacs** [comment]
@casperboone Hi,

in that case I get `Driver [pushover] not supported.` error. It only works if I use fqn. Any more ideas how to solve this issue?

**Comment by casperboone** [comment]
Could you share what your notification class looks like?

I just created a clean Laravel application where I installed the package, added the `AccountApproved` notification class that is in the readme, and executed the line of code from my previous comment. That worked without any issues.

**Comment by gabrieltakacs** [comment]
```
<?php

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Notification;
use NotificationChannels\Pushover\PushoverChannel;
use NotificationChannels\Pushover\PushoverMessage;

class SendPacketStatusChangedNotifications extends Notification implements ShouldQueue
{
    use Queueable;

    /** @var OrderInterface $order */
    protected $order;

    public function __construct(OrderInterface $order)
    {
        $this->order = $order;
    }

    public function via($notifiable)
    {
        return [PushoverChannel::class];
    }

    public function toPushover($notifiable)
    {
      // ...
    }
}

```

Calling the notification from this class:

```
<?php

use App\Notifications\AdminAnonymousPushoverNotifiable;
use NotificationChannels\Pushover\PushoverChannel;

class MyClass
{
    public function myMethod(OrderInterface $order)
    {
// Doesn't work
        \Notification::route(PushoverChannel::class, config('notifications.pushover.recipient'))
            ->notify(
                new SendPacketStatusChangedNotifications($order)
            );

// Hack which works
//        $notifiable = new AdminAnonymousPushoverNotifiable();
//        $notifiable->notify(new SendPacketStatusChangedNotifications($order));
    }
}
```

Using Laravel v6.18.43 and `laravel-notification-channels/pushover` @ `2.1.2`

**Comment by casperboone** [comment]
I can reproduce that issue if you also change the fqn in the via method in SendPacketStatusChangedNotifications, but you shouldn't do that.

Using your code example, this should work:
```php
class SendPacketStatusChangedNotifications extends Notification implements ShouldQueue
{
    use Queueable;

    /** @var OrderInterface $order */
    protected $order;

    public function __construct(OrderInterface $order)
    {
        $this->order = $order;
    }

    public function via($notifiable)
    {
        return [PushoverChannel::class];   // DO NOT CHANGE
    }

    public function toPushover($notifiable)
    {
      // ...
    }
}
```

```php
<?php

use App\Notifications\AdminAnonymousPushoverNotifiable;
use NotificationChannels\Pushover\PushoverChannel;

class MyClass
{
    public function myMethod(OrderInterface $order)
    {
        \Notification::route('pushover', config('notifications.pushover.recipient'))
            ->notify(
                new SendPacketStatusChangedNotifications($order)
            );
}
```

All `Notification::route` does is store the key (`'pushover'`) and value (`config('notifications.pushover.recipient')`) in an array in the anonymous notifiable. It does not interact with drivers. It exposes the array through the `routeNotificationFor` method, where my package passes in the `'pushover'` key.

**Comment by gabrieltakacs** [comment]
Yes, not it works! Thanks a lot for your help!
